### ISSUE TITLE
Problem in running pip install -r requirements.txt

### ISSUE THREAD

**Issue by marzim** [marzim/coinage#1]
Fix the issue in running pip install -r requirements.txt.
   `` building 'bcrypt._bcrypt' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mc185104\appdata\local\temp\pip-build-llb7rx\py-bcrypt\set
p.py", line 61, in <module>
        ext_modules = [bcrypt]
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line
1, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", lin
 49, in run
        _build_ext.run(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\python27\lib\distutils\command\build_ext.py", line 448, in build
extensions
        self.build_extension(ext)
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", lin
 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\python27\lib\distutils\command\build_ext.py", line 498, in build
extension
        depends=ext.depends)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initializ

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc9_support.py", line 52
 in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 299, in query_vcv
rsall
        raise ValueError(str(list(result.keys())))
    ValueError: [u'path']

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:
\users\\mc185104\\appdata\\local\\temp\\pip-build-llb7rx\\py-bcrypt\\setup.py';
=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\mc185
04\appdata\local\temp\pip-mmgvzf-record\install-record.txt --single-version-ext
rnally-managed --compile" failed with error code 1 in c:\users\mc185104\appdata
`local\temp\pip-build-llb7rx\py-bcrypt\ ``

**Comment by marzim** [comment]
Fix an issue on my local machine(NCR cebu office)
